import { BlockBreak } from './BlockBreak';
import { BlockHit } from './BlockHit';
import { BlockPlace } from './BlockPlace';
import { Chat } from './Chat';
import { EntityEvent } from './EntityEvent';
import { EntityHit } from './EntityHit';
import { ItemUse } from './ItemUse';
import { ItemUseOn } from './ItemUseOn';
import { PlayerDeath } from './PlayerDeath';
import { PlayerJoin } from './PlayerJoin';
import { PlayerLeave } from './PlayerLeave';
import { ProjectileHit } from './ProjectileHit';
import { Tick } from './Tick';
import { WorldLoad } from './WorldLoad';
export declare const events: {
    BlockBreak: typeof BlockBreak;
    BlockHit: typeof BlockHit;
    BlockPlace: typeof BlockPlace;
    Chat: typeof Chat;
    EntityEvent: typeof EntityEvent;
    EntityHit: typeof EntityHit;
    ItemUse: typeof ItemUse;
    ItemUseOn: typeof ItemUseOn;
    PlayerDeath: typeof PlayerDeath;
    PlayerJoin: typeof PlayerJoin;
    PlayerLeave: typeof PlayerLeave;
    ProjectileHit: typeof ProjectileHit;
    Tick: typeof Tick;
    WorldLoad: typeof WorldLoad;
};
